---
- hosts: mysql
  tasks:
    - name: Clone repository for mysql
      git:
        repo: https://github.com/khanadm/Ansible-Docker-Terrafrom-Jenkins.git
        dest: /home/sarfaraz/khan/
        clone: true
 
      vars:
        ansible_become_pass: "sudo_password"
    - name: Build Docker image
      command: docker build -t mysql /home/sarfaraz/khan/mysql
    - name: Running  Docker container from  image
      command: docker run --name mysql -p 3306:3306 -d mysql


---
- name: Clone Git repository
  hosts: php_application
  
  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/Akki-1332/php-basic-login-signup-with-mysq.git
        dest: /home/ali/khan/
        clone: yes
    - name: Start a container
      shell: |
        cd /home/ali/khan
        docker build -t php_application .
        
