---
- hosts: client1
  tasks:
    - name: Clone repository for mysql
      git:
        repo: https://github.com/khanadm/Ansible-Docker-Terrafrom-Jenkins.git
        dest: /home/sarfaraz/khan/
        clone: true
 
      vars:
        ansible_become_pass: "sudo_password"
    - name: Build Docker image
      command: docker build -t mysql /home/sarfaraz/khan/mysql
    - name: Running  Docker container from  image
      command: docker run --name mysql -p 3306:3306 -d mysql





- hosts: client2
  tasks:
    - name: Clone repository for mysql
      git:
        repo: https://github.com/khanadm/Ansible-Docker-Terrafrom-Jenkins.git
        dest: /home/sarfaraz/khan/
        clone: true

    - name: Fill DB_SERVER in Dockerfile
      lineinfile:
        path: /home/sarfaraz/khan/php-application/Dockerfile
        regexp: '^ENV DB_SERVER='
        line: 'ENV DB_SERVER={{ hostvars[groups.client1.0].ansible_default_ipv4.address if groups.client1|length > 0 else "" }}'
      vars:
        ansible_become_pass: "sudo_password"
    - name: Build Docker image
      command: docker build -t myapp /home/sarfaraz/khan/php-application  
    - name: Build Docker image
      command: docker run --name php_application -p 80:80 -d myapp 

